apiVersion: v1
kind: Service
metadata:
  name: food-ordering
  namespace: food-ordering
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: food-ordering
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
